### ISSUE TITLE
geojson upload shape needs to be above layer_group in vector export

### ISSUE THREAD

**Issue by ldegroot** [datadesk/web-map-maker#133]

**Comment by jschleuss** [comment]
It's there, but it's underneath layer_group

**Comment by jschleuss** [comment]
also, circles need to be used for any point upload (which isn't showing up)

**Comment by jschleuss** [comment]
fixed with https://github.com/datadesk/web-map-maker/commit/aa0f8daf7dd04e6a41849eeec45fb378e02396e6
