### ISSUE TITLE
extra park land being shaded in on SVG export

### ISSUE THREAD

**Issue by ldegroot** [datadesk/web-map-maker#140]
![screen shot 2017-07-11 at 10 26 57 am](https://user-images.githubusercontent.com/869143/28081325-b9910ad8-6623-11e7-9f07-8450b45ee43c.png)

**Comment by ldegroot** [comment]
looks like it may be farm land?

**Comment by jschleuss** [comment]
I think this was resolved by removing "farmland" from the grouping (which was randomly applied to some areas).
