### ISSUE TITLE
inland water areas in SVG when layer turned off

### ISSUE THREAD

**Issue by ldegroot** [datadesk/web-map-maker#141]
![screen shot 2017-07-11 at 5 22 38 pm](https://user-images.githubusercontent.com/869143/28096761-128da97a-6660-11e7-972b-e3118117691e.png)

**Comment by jschleuss** [comment]
fixed with https://github.com/datadesk/web-map-maker/commit/a5dc2b3e226cd82b5ed0044e7bdbb3333ceefaa8
