### ISSUE TITLE
Hole in Angeles National Forest

### ISSUE THREAD

**Issue by jschleuss** [datadesk/web-map-maker#146]
**Map maker**
![la-mapmaker-07-12-2017-33-34-45](https://user-images.githubusercontent.com/695934/28150553-fecd5a1c-6749-11e7-850e-25c2998350fc.png)

**Google Maps**
![screen shot 2017-07-12 at 9 35 38 pm](https://user-images.githubusercontent.com/695934/28150562-15e89356-674a-11e7-828f-931dae8138d9.png)

**Comment by ldegroot** [comment]
fixed. "nature_reserve" was missing from “parks-and-national-forests-not-national-park” in yaml file
