### ISSUE TITLE
new mapmaker geocoder doesn't accept coords

### ISSUE THREAD

**Issue by chrislkeller** [datadesk/web-map-maker#155]

**Comment by jschleuss** [comment]
It used to be in an older version of https://github.com/datadesk/web-map-maker/blob/db4d5cb4ef7cf2b128c17e3f9faba7cd9b05bc14/js/bing-geocodifier.js#L242

Will add this a coord feature to the geocoder itself and bring in a new version

**Comment by jschleuss** [comment]
Fixed with a new release of bing-geocodify [v0.2.3](https://github.com/datadesk/bing-geocodify/releases/tag/0.2.3) https://github.com/datadesk/web-map-maker/commit/c7577c882ebdc2c4c9d6808f3ce0fc544391d69d

**Comment by joemfox** [comment]
yay
