### ISSUE TITLE
Buildings are outlined inconsistently

### ISSUE THREAD

**Issue by joemfox** [datadesk/web-map-maker#165]
I've been turning buildings off because it looks strange to have some of them outlined for seemingly no reason — would be nice to be able to use the layer we did so much work to upload!
![la-mapmaker-07-24-2017-28-51-28](https://user-images.githubusercontent.com/2977115/28549672-8ac6130c-7090-11e7-94b6-e75f2ec5ec0e.png)
![la-mapmaker-07-24-2017-28-51-39](https://user-images.githubusercontent.com/2977115/28549673-8acba27c-7090-11e7-83ca-838b034e5697.png)
![la-mapmaker-07-24-2017-28-52-28](https://user-images.githubusercontent.com/2977115/28549674-8ad084cc-7090-11e7-9e4c-031e8ca09110.png)

**Comment by jschleuss** [comment]
A workaround would be to have building outlines in the layer selector as a checkbox.

**Comment by jschleuss** [comment]
fixed with this https://github.com/datadesk/web-map-maker/commit/e5e84c293a0ad087206a7b5bc91308b3f0f5593e
