### ISSUE TITLE
Large body of water doesn't show up in TX

### ISSUE THREAD

**Issue by ldegroot** [datadesk/web-map-maker#170]
![tx-oops](https://user-images.githubusercontent.com/869143/29735502-2f0a1004-89ae-11e7-9931-0d1d58b5843a.png)

**Comment by ldegroot** [comment]
Reported to mapzen; https://github.com/tilezen/vector-datasource/issues/1383

**Comment by jschleuss** [comment]
This was fixed some time ago.
