### ISSUE TITLE
Avoiding labels from overlapping in multiple sources layer

### ISSUE THREAD

**Issue by raosaeedali** [datadesk/web-map-maker#171]
Quite a comprehensive project with a very sound visualization. However, I would like to know that how have you avoided the conflicts of labels and icons from overlapping with each other when data is loaded from multiple sources. In my project data is being loaded from multiple sources and results in this overlapping of icons and labels.
![screenshot from 2017-09-15 11-37-26](https://user-images.githubusercontent.com/4352381/30469591-6604d55a-9a0a-11e7-83d3-4a953a8322e4.png)

Also, how did you manage to utilize the functionality of tangram.debug.js as I am unable to see the very file in your project.

**Comment by jschleuss** [comment]
Hi @raosaeedali 
I haven't totally figured it out and neither has Mapzen. (But they're working on it).

Our Mexican states layer doesn't have labels, so it's just the borders and doesn't overlap too bad. The neighborhoods are a separate layer and they do overlap if they're turned on (which I've left them off by default).

![la-mapmaker-09-15-2017-09-29-11](https://user-images.githubusercontent.com/695934/30493275-57d2f988-99f8-11e7-9888-31ba979a1fa6.png)
