### ISSUE TITLE
Boundary layer should be above landuse layer

### ISSUE THREAD

**Issue by joemfox** [datadesk/web-map-maker#175]
in svg resulting from vector export
bad:
<img width="393" alt="screen shot 2017-11-15 at 4 01 37 pm" src="https://user-images.githubusercontent.com/2977115/32866825-7781acd8-ca1e-11e7-9f04-695555f72a2f.png">
good:
<img width="395" alt="screen shot 2017-11-15 at 4 01 52 pm" src="https://user-images.githubusercontent.com/2977115/32866836-7ec03dd4-ca1e-11e7-92ff-47f787af05a6.png">

**Comment by tbone** [comment]
I'd also suggest above the water layer, for lakes and stuff

**Comment by jschleuss** [comment]
Fixed with https://github.com/datadesk/web-map-maker/commit/13d5a8e77db3532dc01d9190dcee58c425ccf655
