### ISSUE TITLE
Land use can extend over water tiles

### ISSUE THREAD

**Issue by joemfox** [datadesk/web-map-maker#181]
<img width="1284" alt="screen shot 2018-02-20 at 6 00 36 pm" src="https://user-images.githubusercontent.com/2977115/36459290-0f76eff4-1668-11e8-84ae-f063f576baad.png">

After moving ocean layer up:
<img width="1285" alt="screen shot 2018-02-20 at 6 00 41 pm" src="https://user-images.githubusercontent.com/2977115/36459292-0f8e6332-1668-11e8-80bc-3986801566e1.png">

**Comment by joemfox** [comment]
related to #175

**Comment by jschleuss** [comment]
Fixed with https://github.com/datadesk/web-map-maker/commit/13d5a8e77db3532dc01d9190dcee58c425ccf655
