### ISSUE TITLE
Mexico's state boundaries missing

### ISSUE THREAD

**Issue by CartoonKahuna** [datadesk/web-map-maker#3]
We have U.S. states but no Canadian provinces. Could have used that today.

**Comment by jschleuss** [comment]
we could pull these from natural earth and ping Mapzen to see what the issue is

**Comment by jschleuss** [comment]
Natural Earth does not include Mexican states. Neither does OpenStreetMap (four state boundaries were missing). So, I [created one](https://github.com/jschleuss/mexican-states) from the OSM data available.

**Comment by CartoonKahuna** [comment]
That's very cool! You're very resourceful.


Paul Duginski
paul.duginski@verizon.net




-----Original Message-----

**Comment by jschleuss** [comment]
This if fixed.
