### ISSUE TITLE
Some transit stops disappear around 12 zoom

### ISSUE THREAD

**Issue by joemfox** [datadesk/web-map-maker#33]
![image 3](https://cloud.githubusercontent.com/assets/2977115/21701533/f7f83398-d35a-11e6-9a18-a1dc96fdcc3a.png)
![image 4](https://cloud.githubusercontent.com/assets/2977115/21701535/f93bcaf8-d35a-11e6-85eb-601821db2b4e.png)

**Comment by jschleuss** [comment]
All points show up now, allowing collision
