### ISSUE TITLE
Add github.io support with api key in URL params

### ISSUE THREAD

**Issue by nvkelso** [datadesk/web-map-maker#51]
It would be nice to load https://datadesk.github.io/web-map-maker (a repo setting to show Github pages from the master branch), but paired with UX for providing the necessary Mapzen API key with URL param support so it could be saved as a bookmark after I've configured it with my own key.

**Comment by nvkelso** [comment]
Also, wonderful project, keep up the great work!

**Comment by jschleuss** [comment]
Agreed. Will do!
