### ISSUE TITLE
GeoJSON upload should shift map area?

### ISSUE THREAD

**Issue by seangreene** [datadesk/web-map-maker#56]
I uploaded a geoJSON file of Lake Oroville earthquakes, but the map stayed on the default L.A. area. At first I thought the uploader wasn't working, until I flew to Lake Oroville on the map. Should uploading geoJSON trigger the map to shift to the data points?

**Comment by jschleuss** [comment]
Instead of forcing this, let's add this button and function after upload "Zoom to area"

**Comment by jschleuss** [comment]
added with https://github.com/datadesk/web-map-maker/commit/3d883c6d346a27c5743dc0e5d4533c1d3c973ee7
