### ISSUE TITLE
Silver Lake comes through as "Silverlake"

### ISSUE THREAD

**Issue by jschleuss** [datadesk/web-map-maker#90]
Not our style.

![screen shot 2017-05-02 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/695934/25642046/2f9cd91e-2f4c-11e7-96e3-c0dd2ade1858.png)

**Comment by joemfox** [comment]
https://whosonfirst.mapzen.com/spelunker/id/85865847/#13/34.0944/-118.2673

"Silverlake" is set as the preferred name instead of as a variant. Looks like a mistake, we should see if we can edit it.

**Comment by jschleuss** [comment]
Avoiding because we're using our own data for L.A. neighborhoods
